routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\FilmController;
use App\Http\Controllers\GenreController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('films');
});

Route::get('/home', function () {
    return redirect('films');
});

// Menampilkan halaman login
Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login']);
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

// Rute untuk Genre
Route::resource('genres', GenreController::class)->middleware('auth'); // CRUD for Genre
Route::get('genres', [GenreController::class, 'index'])->name('genres.index');
Route::get('genres/create', [GenreController::class, 'create'])->name('genres.create');
Route::post('genres', [GenreController::class, 'store'])->name('genres.store');
Route::get('genres/{genre}', [GenreController::class, 'show'])->name('genres.show');
Route::get('genres/{genre}/edit', [GenreController::class, 'edit'])->name('genres.edit');
Route::put('genres/{genre}', [GenreController::class, 'update'])->name('genres.update');
Route::delete('genres/{genre}', [GenreController::class, 'destroy'])->name('genres.destroy');

// Rute untuk Film
Route::resource('films', FilmController::class)->middleware('auth')->except(['index', 'show']);
Route::get('films', [FilmController::class, 'index']);
Route::get('films/create', [FilmController::class, 'create'])->name('films.create');
Route::get('films/show/{id}', [FilmController::class, 'show']);
Route::get('films/edit/{film}', [FilmController::class, 'edit'])->name('films.edit');
Route::put('films/update/{film}', [FilmController::class, 'update'])->name('films.update');
Route::get('films/destroy/{film}', [FilmController::class, 'destroy'])->name('films.destroy');
Route::get('films/reviews/{film}', [FilmController::class, 'showReviews'])->name('films.reviews');
Route::get('films/add-review/{id}', [FilmController::class, 'createReviewForm'])->name('films.create_review');
Route::post('films/reviews/store', [FilmController::class, 'storeReview']);

app/Models/Film.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Film extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'description', 'genre_id'];

    public function genre()
    {
        return $this->belongsTo(Genre::class);
    }

    public function reviews()
    {
        return $this->hasMany(Review::class);
    }
}

app/Http/Controllers/FilmController.php
<?php

namespace App\Http\Controllers;

use App\Models\Film;
use App\Models\Genre;
use App\Models\Review;
use App\Models\User;
use Illuminate\Http\Request;

class FilmController extends Controller
{
    public function index()
    {
        $films = Film::all();
        return view('films.index', compact('films'));
    }

    public function show($id)
    {
        $film = Film::findOrFail($id);
        $genreName = $film->genre->name;
        $reviews = $film->reviews;
        return view('films.show', compact('film', 'genreName', 'reviews'));
    }

    public function create()
    {
        $genres = Genre::all();
        return view('films.create', compact('genres'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'description' => 'required|string',
            'genre_id' => 'required|exists:genres,id',
        ]);

        Film::create([
            'title' => $request->title,
            'description' => $request->description,
            'genre_id' => $request->genre_id,
        ]);

        return redirect('films')
            ->with('success', 'Film added successfully');
    }

    public function edit($id)
    {
        $genres = Genre::all();
        $film = Film::findOrFail($id);
        return view('films.edit', compact(['film', 'genres']));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'description' => 'required|string',
            'genre_id' => 'required|exists:genres,id',
        ]);

        $film = Film::findOrFail($id);
        $film->update([
            'title' => $request->title,
            'description' => $request->description,
            'genre_id' => $request->genre_id,
        ]);

        return redirect('films')
            ->with('success', 'Film updated successfully');
    }

    public function destroy($id)
    {
        $film = Film::findOrFail($id);
        $film->delete();

        return redirect('films')
            ->with('success', 'Film deleted successfully');
    }

    public function showReviews(Film $film)
    {
        $reviews = $film->reviews;

        return view('films.reviews', compact('film', 'reviews'));
    }

    public function createReviewForm($id)
    {
        $film = Film::findOrFail($id);
        return view('reviews.create', compact('film'));
    }

    public function storeReview(Request $request)
    {

        Review::create([
            'film_id' => $request->film_id,
            'user_id' => $request->user_id,
            'comment' => $request->comment,
            'rating' => $request->rating,
        ]);

        return redirect('/films/show/' . $request->film_id)
            ->with('success', 'Review added successfully');
    }
}

resources/views/films/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container bg-white p-3">
        <h2>Create a New Film</h2>
        <form action="{{ route('films.store') }}" method="post">
            @csrf
            <div class="form-group mt-3">
                <label for="title">Title:</label>
                <input type="text" class="form-control" name="title" id="title" required>
            </div>

            <div class="form-group mt-3">
                <label for="description">Description:</label>
                <textarea class="form-control" name="description" id="description" rows="4" required></textarea>
            </div>

            <div class="form-group mt-3">
                <label for="genre_id">Genre:</label>
                <select class="form-control" name="genre_id" id="genre_id" required>
                    @foreach ($genres as $genre)
                        <option value="{{ $genre->id }}">{{ $genre->name }}</option>
                    @endforeach
                </select>
            </div>

            <button type="submit" class="btn btn-success mt-3">Create Film</button>

        </form>
    </div>
@endsection

resources/views/films/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container bg-white p-3">
        <h2>Edit Film</h2>
        <form action="{{ route('films.update', $film->id) }}" method="post">
            @csrf
            @method('put')
            <div class="form-group mt-3">
                <label for="title">Title:</label>
                <input type="text" class="form-control" name="title" id="title" value="{{ $film->title }}" required>
            </div>

            <div class="form-group mt-3">
                <label for="description">Description:</label>
                <textarea class="form-control" name="description" id="description" rows="4" required>{{ $film->description }}</textarea>
            </div>

            <div class="form-group mt-3">
                <label for="genre_id">Genre:</label>
                <select class="form-control" name="genre_id" id="genre_id" required>
                    @foreach ($genres as $genre)
                        <option value="{{ $genre->id }}" {{ $film->genre_id == $genre->id ? 'selected' : '' }}>
                            {{ $genre->name }}
                        </option>
                    @endforeach
                </select>
            </div>

            <button type="submit" class="btn btn-primary mt-3">Update Film</button>

        </form>
    </div>
@endsection

resources/views/films/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col">
                <h2>List of Films</h2>
            </div>
            @auth
                <div class="col">
                    <a href="/films/create" class="btn btn-primary float-end">+ Film</a>
                    <a href="/genres" class="btn btn-primary float-end me-2">+ Genre</a>
                </div>
            @endauth


        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Genre</th>
                        @auth
                            <th>Action</th>
                        @endauth
                    </tr>
                </thead>
                <tbody>
                    @foreach ($films as $film)
                        <tr>
                            <td>{{ $film->title }}</td>
                            <td>{{ $film->description }}</td>
                            <td>{{ $film->genre->name }}</td>
                            @auth
                                <td class="float-end">
                                    <a href="films/show/{{ $film->id }}" class="btn btn-primary btn-sm">View
                                        Details</a>
                                    <a href="films/edit/{{ $film->id }}" class="btn btn-warning btn-sm">Edit</a>
                                    <a href="films/destroy/{{ $film->id }}" class="btn btn-danger btn-sm"
                                        onclick="return confirm('Apakah anda yakin?')">Hapus</a>
                                </td>
                            @endauth
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/films/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ $film->title }}</div>

                    <div class="card-body">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <th>Description</th>
                                    <td>{{ $film->description }}</td>
                                </tr>
                                <tr>
                                    <th>Genre</th>
                                    <td>{{ $genreName }}</td>
                                </tr>
                            </tbody>
                        </table>

                        <div class="row">
                            <div class="col">
                                <h3>Reviews</h3>
                            </div>
                            <div class="col">
                                <a href="/films/add-review/{{ $film->id }}"
                                    class="btn btn-primary btn-sm float-end">Buat
                                    Review</a>
                            </div>
                        </div>

                        @if (count($reviews) > 0)
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>User</th>
                                        <th>Comment</th>
                                        <th>Rating</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($reviews as $review)
                                        <tr>
                                            <td>{{ $review->user->name }}</td>
                                            <td>{{ $review->comment }}</td>
                                            <td>{{ $review->rating }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @else
                            <p>No reviews available.</p>
                        @endif

                        <p><a href="{{ url('/') }}">Back to List</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection